gamesdb/gamesdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import patterns
from django.contrib.auth.views import login, logout
from mygamesdb.views import*
from django.contrib.auth.forms import UserCreationForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', mainpage),
    url(r'^gamesdb/', include('mygamesdb.urls', namespace = 'gamesdb')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
    url('^register/', CreateView.as_view(
        template_name='register.html',
        form_class=UserCreationForm,
        success_url='/gamesdb/'),name='register'),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, })
    ]

gamesdb/mygamesdb/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView, UpdateView
from models import Game, Developer, Platform
from views import *
from mygamesdb import views

urlpatterns = [

    url(r'^$',
        GamesList.as_view(),
        name='games_list'),

    url(r'^api\.(?P<extension>(json|xml|html))/$',
        GamesList.as_view(),
        name='games_list_api'),

    url(r'^developers/$',
        DevelopersList.as_view(),
        name='developers_list'),

    url(r'^developersapi\.(?P<extension>(json|xml|html))/$',
        DevelopersList.as_view(),
        name='developers_list_api'),

    url(r'^platforms/$',
        PlatformsList.as_view(),
        name='platforms_list'),

    url(r'^platformsapi\.(?P<extension>(json|xml|html))/$',
        PlatformsList.as_view(),
        name='platforms_list_api'),

    url(r'^games/(?P<pk>[a-zA-Z0-9 ]+)/$',
        GameDetail.as_view(),
        name='games_detail'),

    url(r'^developers/(?P<pk>[a-zA-Z0-9 ]+)/$',
        DeveloperDetail.as_view(),
        name='developers_detail'),

    url(r'^platforms/(?P<pk>[a-zA-Z0-9 ]+)/$',
        PlatformDetail.as_view(),
        name='platforms_detail'),

    url(r'^games/(?P<pk>[a-zA-Z0-9 ]+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Game,
            template_name='mygamesdb/form.html',
            form_class=GameForm),
        name='game_edit'),

    url(r'^developers/(?P<pk>[a-zA-Z0-9 ]+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Developer,
            template_name='mygamesdb/form.html',
            form_class=DeveloperForm),
        name='developer_edit'),

    url(r'^platforms/(?P<pk>[a-zA-Z0-9 ]+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Platform,
            template_name='mygamesdb/form.html',
            form_class=PlatformForm),
        name='platform_edit'),

    url(r'^gamesapi/(?P<pk>[a-zA-Z0-9 ]+)\.(?P<extension>(json|xml|html))/$',
        GameDetail.as_view(),
        name='games_detail_api'),

    url(r'^developersapi/(?P<pk>[a-zA-Z0-9 ]+)\.(?P<extension>(json|xml|html))/$',
        DeveloperDetail.as_view(),
        name='developers_detail_api'),

    url(r'^platformsapi/(?P<pk>[a-zA-Z0-9 ]+)\.(?P<extension>(json|xml|html))/$',
        PlatformDetail.as_view(),
        name='platforms_detail_api'),

    url(r'^gamesdb/create/$',
        GameCreate.as_view(),
        name='game_create'),

    url(r'^gamesdb/developers/create/$',
        DeveloperCreate.as_view(),
        name='developer_create'),

    url(r'^gamesdb/platforms/create/$',
        PlatformCreate.as_view(),
        name='platform_create'),

    url(r'^games/(?P<pk>[a-zA-Z0-9 ]+)/delete/$',
        GameDelete.as_view(),
        name='game_delete'),

    url(r'^developers/(?P<pk>[a-zA-Z0-9 ]+)/delete/$',
        DeveloperDelete.as_view(),
        name='developer_delete'),

    url(r'^platforms/(?P<pk>[a-zA-Z0-9 ]+)/delete/$',
        PlatformDelete.as_view(),
        name='platform_delete'),

    url(r'^games/(?P<pk>[a-zA-Z0-9 ]+)/reviews/create/$',
        review,
        name='review_create'),

    # url(r'^delete_game/(?P<pk>\d+)/$',
    #     'views.delete_game',
    #     name='delete_game')
]

gamesdb/mygamesdb/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date


class Developer(models.Model):
    id = models.TextField(unique=True, primary_key=True)
    developer_name = models.TextField()
    fundation_year = models.TextField(blank=True, null=True)
    founder = models.TextField(blank=True, null=True)
    city = models.TextField(blank=True, null=True)
    province_or_state = models.TextField(blank=True, null=True)
    country = models.TextField(blank=True, null=True)    
    videogame_genere_preferences = models.TextField(blank=True, null=True)
    average_videogames_rating = models.TextField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to="media", blank=True, null=True)
    ins_creator = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return u"%s" % self.id

    def get_absolute_url(self):
        return reverse('gamesdb:developers_detail', kwargs={'pk': self.pk})


class Platform(models.Model):
    id = models.TextField(unique=True, primary_key=True)
    console_name = models.TextField()
    controller = models.TextField(blank=True, null=True)
    generation = models.TextField(blank=True, null=True)
    developer = models.ForeignKey(Developer, default=1)
    manufacturer = models.TextField(blank=True, null=True)
    cpu = models.TextField(blank=True, null=True)
    memory = models.TextField(blank=True, null=True)
    graphics = models.TextField(blank=True, null=True)
    sound = models.TextField(blank=True, null=True)
    display = models.TextField(blank=True, null=True)
    rating = models.TextField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to="media", blank=True, null=True)
    ins_creator = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return u"%s" % self.id

    def get_absolute_url(self):
        return reverse('gamesdb:platforms_detail', kwargs={'pk': self.pk})


class Game(models.Model):
    id = models.TextField(unique=True, primary_key=True)
    game_title = models.TextField()
    platform = models.ForeignKey(Platform, default=1)
    release_date = models.TextField(blank=True, null=True)
    ESRB = models.TextField(blank=True, null=True)
    generes = models.TextField(blank=True, null=True)
    trailer = models.URLField(blank=True, null=True)
    developer = models.ForeignKey(Developer, default=1)
    rating = models.TextField(blank=True, null=True)
    updates = models.TextField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to="media", blank=True, null=True)
    ins_creator = models.ForeignKey(User, default=1)

    def __unicode__(self):
        return u"%s" % self.id

    def get_absolute_url(self):
        return reverse('gamesdb:games_detail', kwargs={'pk': self.pk})

    def average_rating(self):
        ratingSum = sum([float(review.rating) for review in self.gamereview_set.all()])
        reviewCount = self.gamereview_set.count()
        return ratingSum / reviewCount


class Review(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)


class GameReview(Review):
    game = models.ForeignKey(Game)

gamesdb/mygamesdb/forms.py
from django.forms import ModelForm
from models import Developer, Game, Platform


class GameForm(ModelForm):
    class Meta:
        model = Game
        exclude = ('ins_creator',)


class DeveloperForm(ModelForm):
    class Meta:
        model = Developer
        exclude = ('ins_creator',)


class PlatformForm(ModelForm):
    class Meta:
        model = Platform
        exclude = ('ins_creator',)

gamesdb/mygamesdb/views.py
from django.views.generic import DetailView, ListView
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.base import TemplateResponseMixin
from django.core import serializers
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import redirect
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from models import Developer, Platform, Game, GameReview
from forms import *
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator


class ConnegResponseMixin(TemplateResponseMixin):

    def render_json_object_response(self, objects, **kwargs):
        json_data = serializers.serialize(u"json", objects, **kwargs)
        return HttpResponse(json_data, content_type=u"application/json")

    def render_xml_object_response(self, objects, **kwargs):
        xml_data = serializers.serialize(u"xml", objects, **kwargs)
        return HttpResponse(xml_data, content_type=u"application/xml")

    def render_to_response(self, context, **kwargs):
        if 'extension' in self.kwargs:
            try:
                objects = [self.object]
            except AttributeError:
                objects = self.object_list
            if self.kwargs['extension'] == 'json':
                return self.render_json_object_response(objects=objects)
            elif self.kwargs['extension'] == 'xml':
                return self.render_xml_object_response(objects=objects)
        return super(ConnegResponseMixin, self).render_to_response(context)


class LoginRequiredMixin(object):
    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


class CheckIsOwnerMixin(object):
    def get_object(self, *args, **kwargs):
        obj = super(CheckIsOwnerMixin, self).get_object(*args, **kwargs)
        if not obj.ins_creator == self.request.user:
            raise PermissionDenied
        return obj


class LoginRequiredCheckIsOwnerUpdateView(LoginRequiredMixin, CheckIsOwnerMixin, UpdateView):
    template_name = 'mygamesdb/form.html'


def mainpage(request):
    return render(request, 'mygamesdb/mainpage.html')


class GamesList(ListView, ConnegResponseMixin):
    model = Game
    queryset = Game.objects.all()
    context_object_name = 'games'
    template_name = 'mygamesdb/games_list.html'


class DevelopersList(ListView, ConnegResponseMixin):
    model = Developer
    queryset = Developer.objects.all()
    context_object_name = 'developers'
    template_name = 'mygamesdb/developers_list.html'


class PlatformsList(ListView, ConnegResponseMixin):
    model = Platform
    queryset = Platform.objects.all()
    context_object_name = 'platforms'
    template_name = 'mygamesdb/platforms_list.html'


class GameDetail(DetailView, ConnegResponseMixin):
    model = Game
    context_object_name = 'game'
    template_name = 'mygamesdb/games_detail.html'

    def get_context_data(self, **kwargs):
        context = super(GameDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = GameReview.RATING_CHOICES
        return context


class DeveloperDetail(DetailView, ConnegResponseMixin):
    model = Developer
    context_object_name = 'developer'
    template_name = 'mygamesdb/developers_detail.html'


class PlatformDetail(DetailView, ConnegResponseMixin):
    model = Platform
    context_object_name = 'platform'
    template_name = 'mygamesdb/platforms_detail.html'


class GameCreate(LoginRequiredMixin, CreateView):
    model = Game
    template_name = 'mygamesdb/form.html'
    form_class = GameForm

    def form_valid(self, form):
        form.instance.ins_creator = self.request.user
        return super(GameCreate, self).form_valid(form)


class DeveloperCreate(LoginRequiredMixin, CreateView):
    model = Developer
    template_name = 'mygamesdb/form.html'
    form_class = DeveloperForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(DeveloperCreate, self).form_valid(form)


class PlatformCreate(LoginRequiredMixin, CreateView):
    model = Platform
    template_name = 'mygamesdb/form.html'
    form_class = PlatformForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(PlatformCreate, self).form_valid(form)


class GameDelete(LoginRequiredMixin, CheckIsOwnerMixin, DeleteView):
    model = Game
    success_url = reverse_lazy('gamesdb:games_list')


class DeveloperDelete(LoginRequiredMixin, CheckIsOwnerMixin, DeleteView):
    model = Developer
    success_url = reverse_lazy('gamesdb:developers_list')


class PlatformDelete(LoginRequiredMixin, CheckIsOwnerMixin, DeleteView):
    model = Platform
    success_url = reverse_lazy('gamesdb:platforms_list')


def review(request, pk):
    game = get_object_or_404(Game, pk=pk)
    review = GameReview(
        rating=request.POST['rating'],
        game=game)
    review.save()
    return HttpResponseRedirect(reverse('gamesdb:games_detail', args=(game.id,)))

gamesdb/mygamesdb/templates/mygamesdb/developer_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete {{ object.developer_name }}</title>
    <form action="" method="post">{% csrf_token %}
    <h2><p>Are you sure you want to delete "{{ object.developer_name }}"?</p></h2>
    <input type="submit" value="Confirm" />
    </form>
    <br>
    <button type="button"><a href='/gamesdb/developers'> Not yet </a></button>
    </form>
</head>
<body>

</body>
</html>

gamesdb/mygamesdb/templates/mygamesdb/developers_detail.html
<html>
  <head>
    <title>Developers</title>
  </head>
  <body>
  <span vocab="http://schema.org/" typeof="Organization">
    <h1>Developer
        {% if user == object.ins_creator %}
            (<a href="{% url 'gamesdb:developer_edit' object.id %}">edit</a>)
            (<a href="{% url 'gamesdb:developer_delete' object.id %}">delete</a>)
        {% endif %}
    </h1>
    <h2><span property="name"> {{ object.developer_name }}</span> </h2>
    {%	if object.image %}
    	<span rel="image">
      	<span vocab="http://schema.org/" typeof="ImageObject">
        	<p><img	src="{{object.image.url}}" width="300px"/></p></span></span>
    {%	endif	%}
    <ul>
      <li>
        <b>Id:</b> {{ object.id }}
      </li>
      <li>
        <b>Fundation year:</b><span property="foundingDate"> {{ object.fundation_year }}</span>
      </li>
      <li>
        <b>Founder:</b> <span property ="founder">{{ object.founder }}</span>
      </li>
      <li>
      	<span vocab="http://schema.org/" typeof="Place">
        <b>City:</b><span property = "name"> {{ object.city }}</span></span>
      </li>
      <li>
        <b>Province or State:</b> {{ object.province_or_state }}
      </li>
      <li>
        <b>Country:</b> {{ object.country }}
      </li>
      <li>
        <b>Video game genere preferences:</b> {{ object.videogame_genere_preferences }}
      </li>
      <li>
        <b>Average rating:</b> {{ object.average_videogames_rating }}
      </li>
       <li>
        <b>Website:</b>
         <a href="{{object.website}}" target="_blank"> {{object.website}}</a>
      </li>
      <br>
      <h3>Developes for platforms:</h3>
              {% for platform in object.platform_set.all %}
                <li><a href="{% url 'gamesdb:platforms_detail' platform.id %}">{{ platform.console_name }}</a></li>
              {% empty %}
                <li>Sorry, no platforms for this developer.</li>
            {% endfor %}
      <br>
      <h3>List of games</h3>
              {% for game in object.game_set.all %}
                <li><a href="{% url 'gamesdb:games_detail' game.id %}"> {{ game.game_title }}</a></li>
              {% empty %}
                <li>Sorry, no games for this developer yet.</li>
            {% endfor %}
      </span>
      <br>
      <a href='/gamesdb/developers'> More video game developers </a>
      <br>
      <a href='/gamesdb'> Home </a>
      </span>
  </body>
</html>

gamesdb/mygamesdb/templates/mygamesdb/developers_list.html
<html>
  <head>
    <title> GamesDB </title>
      <h1> GamesDB </h1>
  </head>
  <body background="http://www.wallpaperfo.com/thumbnails/detail/20120427/video%20games%20valve%20corporation%20portal%20companion%20cube%20portal%202%20valve%201920x1080%20wallpaper_www.wallpaperfo.com_98.jpg">
    <h2 style="text-indent: 1em">Video game developers
    {% if user %}(<a href="{% url 'gamesdb:developer_create' %}">add</a>){% endif %}
    </h2>
    {% if developers %}
    <ul>
    {% for developer in developers %}
    <li>
    <a href="{% url "gamesdb:developers_detail" developer.id%}"> {{developer.developer_name}} </a>
    </li>
    {% endfor %}
    </ul>
    {% else %}
    <p style="text-indent: 2em">No hi ha cap developer</p>
    {% endif %}
    
    <br>
      <a href='/gamesdb'> Home </a>
  </body>
</html>

gamesdb/mygamesdb/templates/mygamesdb/form.html
<head>
    <link rel="stylesheet"
        href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"	/>
    <script	src="http://code.jquery.com/jquery-2.2.3.js"></script>
    <script	src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

{% block content %}
<
    <script>
        $(function(){
           var	genres = ["rol playing game", "first person shooter","first person action",	"terror"];
              $("#id_generes").autocomplete({
                source:	genres
           });


            $("#id_city").autocomplete({
                source: function(request, response) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "demo"
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    provinceName: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui) {
                    if (ui.item) {
                        $("#id_province_or_state").val(ui.item.provinceName);
                        $("#id_country").val(ui.item.countryName);
                    }
                }
            });
        });
    </script>
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

gamesdb/mygamesdb/templates/mygamesdb/game_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete {{ object.game_title }} </title>
    <form action="" method="post">{% csrf_token %}
    <h2><p>Are you sure you want to delete "{{ object.game_title }}"?</p></h2>
    <input type="submit" value="Confirm" />
    </form>
    <br>
    <button type="button"><a href='/gamesdb'> Not yet </a></button>
    </form>
</head>
<body>

</body>
</html>

gamesdb/mygamesdb/templates/mygamesdb/games_detail.html
<html>
  <head>
    <title>Video Games Detail</title>
  </head>
  <body>
  <span vocab="http://schema.org/" typeof="VideoGame">
    <h1><span property="applicationCategory">Video Game</span>
        {% if user == object.ins_creator %}
            (<a href="{% url 'gamesdb:game_edit' object.id %}">edit</a>)
            (<a href="{% url 'gamesdb:game_delete' object.id %}">delete</a>)
        {% endif %}
    </h1>
        <span property="name"><h2>{{ object.game_title }}</h2> </span>
    {% if object.image %}
    	<span rel="image">
      <span vocab="http://schema.org/" typeof="ImageObject">
        <p><img	src="{{object.image.url}}" width="300px"/></p></span></span>
    {%	endif	%}
    <ul>
      <li>
        <b>Id:</b> {{ object.id }}
      </li>
      <li> <b>Developer:</b>
      <span rel="producer">
      <span vocab="http://schema.org/" typeof="Organization">
      <span property="name">
       <a href="{% url "gamesdb:developers_detail" object.developer.id%}">  {{object.developer.developer_name}} </a></span></span></span>
      </li>
      <li>
        <b>Platform:</b>
        <span property="gamePlatform">
        <a href="{% url "gamesdb:platforms_detail" object.platform.id%}">  {{object.platform.console_name}} </a>
           </span>
      </li>
      <li>
        <b>Release date:</b> <span property="dateCreated">{{ object.release_date }}</span>
      </li>
      <li>
       <b>ESRB:</b> <span property="contentRating">{{ object.ESRB }}</span>
      </li>
      <li>
        <b>Genre:</b> <span property="genre">{{ object.generes }}</span>
      </li>
      <li>
        <b>Trailer:</b>
        <a href="{{object.trailer}}" target="_blank"> {{object.trailer}} </a>
      </li>
      <li>
        <b>Updates:</b> <span property="version">{{ object.updates }}</span>
      </li>
      <li>
        <b>Website:</b>
        <span property="gameLocation"><a href="{{object.website}}" target="_blank"  > {{object.website}} </a></span>
      </li>
    <h3>Rating</h3>
    {% if object.gamereview_set.all|length > 0 %}
    <span rel="aggregateRating">
         <p typeof="AggregateRating">
         <b>Average rating:</b>
        <span property="ratingValue">{{ object.average_rating|stringformat:".1f" }}</span>
         {% with object.gamereview_set.all|length as reviewCount %}
         (<span property="reviewCount">{{ reviewCount }}
        </span> vote{{ reviewCount|pluralize }} done)
         {% endwith %}
         </p>
    </span>
        {% else %}
        <p>No votes yet</p>
    {%  endif %}
        <form action="{% url 'gamesdb:review_create' object.id %}" method="post">
        {% csrf_token %}
        <p><b>Vote:</b></p>
        <p>{% for rate in RATING_CHOICES %}
            <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.0 }}" />
            <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{ rate.0|pluralize }}</label>
        <br/>{% endfor %}
        </p>
        <input type="submit" value="Review" />
        </form>
    </ul>
     <span rel="author">
      <span vocab="http://schema.org/" typeof="Person">

    <p> Post created by <span property="name">{{ object.ins_creator }}</p>
    </span></span></span>

    </span>
    <br>
    <a href='/gamesdb'> Home </a>
  </body>
</html>

gamesdb/mygamesdb/templates/mygamesdb/games_list.html
<html>
  <head>
    <title> GamesDB </title>
      <h1> GamesDB </h1>
  </head>
  {% block header %}
    {% if user.username %}
        <p>You are logged as: <b>{{ user.username }} </b>| <a href="{% url 'logout' %}?next={{request.path}}">Logout</a></p>
    {% else %}
        <p><a href="{% url 'register' %}"  class="top-menu">Sign up<span class="glyphicon glyphicon-plus"></span></a>
        <p><a href="{% url 'login' %}?next={{request.path}}">Login</a></p>{% endif %}

  {% endblock %}
  <body background="https://images5.alphacoders.com/438/438934.jpg">
    <h2 style="text-indent: 1em">Video games
    {% if user %}(<a href="{% url 'gamesdb:game_create' %}">add</a>){% endif %}
    </h2>
    {% if games %}
    <ul>
    {% for game in games %}
    <li>
    <a href="{% url "gamesdb:games_detail" game.id%}"> {{game.game_title}} </a>
    </li>
    {% endfor %}
    </ul>
    {% else %}
    <p style="text-indent: 2em">No hi ha cap videojoc</p>
    {% endif %}
    <h2 style="text-indent: 1em"> Search for developer </h2>
    {% block sidebar %}<ul><a href="/gamesdb/developers">Developer list</a></ul>{% endblock %}
    <h2 style="text-indent: 1em"> Search for platform </h2>
    <ul><a href="/gamesdb/platforms">Platform list</a></ul>
    <div id="header"></div>
    <br>
    <a href='/'> Mainpage </a>
  </body>
</html>

gamesdb/mygamesdb/templates/mygamesdb/platforms_detail.html
<html>
  <head>
    <title>Platforms Detail</title>
  </head>
  <body>
    <h1>Platform
        {% if user == object.ins_creator %}
            (<a href="{% url 'gamesdb:platform_edit' object.id %}">edit</a>)
            (<a href="{% url 'gamesdb:platform_delete' object.id %}">delete</a>)
        {% endif %}
    </h1>
    <h2>{{ object.console_name }}</h2>
    {%	if object.image %}
        <p><img	src="{{object.image.url}}" width="300px"/></p>
    {%	endif	%}
    <ul>
    <ul>
      <li>
        <b>Id:</b> {{ object.id }}
      </li>
      <li>
        <b>Controller:</b> {{ object.controller }}
      </li>
      <li>
        <b>Generation:</b> {{ object.generation }}
      </li>
      <li>
        <b>Manufacturer:</b> {{ object.manufacturer }}
      </li>
      <li>
        <b>Cpu:</b> {{ object.cpu }}
      </li>
      <li>
        <b>Memory:</b> {{ object.memory }}
      </li>
      <li>
        <b>Graphics:</b> {{ object.graphics }}
      </li>
      <li>
        <b>Sound:</b> {{ object.sound }}
      </li>
      <li>
        <b>Rating:</b> {{ object.rating }}
      </li>
      <li>
        <b>Website:</b>
        <a href="{{object.website}}" target="_blank"> {{object.website}} </a>
      </li>
    </ul>

    <h3>List of games</h3>
              {% for game in object.game_set.all %}
                <li><a href="{% url 'gamesdb:games_detail' game.id %}" >{{ game.game_title }}</a></li>
              {% empty %}
                <li>Sorry, no games for this platform yet.</li>
            {% endfor %}

    <p> Post created by {{ object.ins_creator }}</p>
    <br>
      <a href='/gamesdb/platforms'> More video game platforms </a>

      <br>
      <a href='/gamesdb'> Home </a>
  </body>
</html>

gamesdb/mygamesdb/templates/mygamesdb/platforms_list.html
<html>
  <head>
    <title> GamesDB </title>
      <h1> GamesDB </h1>
  </head>
  <body background="http://sf.co.ua/14/05/wallpaper-287079.jpg">
    <h2 style="text-indent: 1em">Video game platforms
    {% if user %}(<a href="{% url 'gamesdb:platform_create' %}">add</a>){% endif %}
    </h2>
    {% if platforms %}
    <ul>
    {% for platform in platforms %}
    <li>
    <a href="{% url "gamesdb:platforms_detail" platform.id%}"> {{platform.console_name}} </a>
    </li>
    {% endfor %}
    </ul>
    {% else %}
    <p style="text-indent: 2em">No hi ha cap plataforma</p>
    {% endif %}
    
    <br>
      <a href='/gamesdb'> Home </a>
  </body>
</html>